# -*- coding: utf-8 -*-
"""GuessTheGame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m9Mxn5xYxrvCR2gSbEz2-RcDJPVurTAW
"""

import streamlit as st
import random

def guess_number_streamlit():
    st.title("Guess the Number Game!")
    st.write("I'm thinking of a number between 1 and 100. Try to guess it!")

    talaaterbah = 23  # The secret number
    guess = st.number_input("Enter your guess:", min_value=1, max_value=100, step=1)

    if st.button("Guess"):
        if guess < talaaterbah:
            st.write("Your guess is too low.")
        elif guess > talaaterbah:
            st.write("Your guess is too high.")
        else:
            st.success("That's it! You guessed correctly!")

if __name__ == "__main__":
    guess_number_streamlit()